function [state0, params0] = initializeLander(overrides)
%INITIALIZELANDER Build a default initial state and parameter struct.
%
%   [state0, params0] = initializeLander()
%   [state0, params0] = initializeLander(overrides)
%
%   overrides (optional) is a struct whose fields overwrite the defaults
%   below, e.g.:
%       [s0, p0] = initializeLander(struct('dryMass', 900, 'Tmax', 20000));
%   Fields not present in overrides keep their default value. Fields in
%   overrides that are not part of the defaults are still copied through,
%   so Person 2/Person 4 can attach extra fields (e.g. a landing-pad
%   x-position) without this function rejecting the struct.
%
%   DEFAULT INITIAL STATE (ordering fixed by the project spec):
%       state0 = [x; vx; y; vy; theta; omega] = [0; 0; 100; 0; 0; 0]
%       (lander starts 100 m above the surface, at rest, upright)
%
%   DEFAULT PARAMETERS (SI units - all are placeholder/reasonable values
%   for a university project and can be freely overridden; see
%   documentation/PHYSICS_ENGINE.md "Assumptions" for the reasoning):
%       g                 = 1.62    m/s^2   (lunar gravity, fixed by spec)
%       dt                = 0.04    s       (fixed by spec)
%       dryMass           = 1500    kg
%       fuelMass          = 500     kg
%       mass              = dryMass + fuelMass
%       ve                = 3000    m/s     (~306 s Isp equivalent)
%       I                 = 500     kg*m^2
%       Tmax              = 15000   N
%       tauMax            = 500     N*m
%       thetaMax          = 0.5236  rad (30 deg)
%       integrationMethod = 'Euler'

    if nargin < 1
        overrides = struct();
    end
    if ~isstruct(overrides) || ~isscalar(overrides)
        error('PhysicsEngine:InvalidParams', 'overrides must be a scalar struct.');
    end

    dryMass  = 1500;
    fuelMass = 500;

    params0 = struct( ...
    'g',                 1.62, ...
    'dt',                0.04, ...
    'Np',                70, ...
    'Nc',                12, ...
    'Q', diag([30 220 60 260 180 35]), ...
'R', diag([0.015 0.04]), ...
'S', diag([0.02 0.04]), ...
    'dryMass',           dryMass, ...
    'fuelMass',          fuelMass, ...
    'mass',              dryMass + fuelMass, ...
    've',                3000, ...
    'I',                 500, ...
    'Tmax',              15000, ...
    'tauMax',             500, ...
    'thetaMax',            0.5236, ...
    'integrationMethod',  'Euler', ...
    'target',            struct('x', 0, 'y', 0, 'halfWidth', 7, 'centerHeight', 4.5), ...
    'landerBody',        [ ...
        -2.9 -2.8;  2.9 -2.8;  2.9  2.8; -2.9  2.8], ...
    'landerGeometry',    struct( ...
        'bodyWidth',       5.8, ...
        'bodyBottom',     -2.8, ...
        'bodyTop',         2.8, ...
        'noseHeight',      2.0, ...
        'legAttachY',     -2.35, ...
        'legAttachX',     [-2.0 0 2.0], ...
        'footX',          [-3.4 0 3.4], ...
        'footY',          -5.3, ...
        'footPadHalfWidth', 0.75, ...
        'legThickness',    7.0, ...
        'footThickness',   8.0, ...
        'legAzimuthDeg',   [90 210 330]), ...
    'landing',            struct( ...
        'vyMax',            0.60, ...
        'vxMax',            0.20, ...
        'thetaMax',         0.005, ...
        'omegaMax',         0.08, ...
        'footHeightTol',    0.03, ...
        'footPenetrationTol', 0.02));

    overrideNames = fieldnames(overrides);
    for k = 1:numel(overrideNames)
        params0.(overrideNames{k}) = overrides.(overrideNames{k});
    end

    % If the caller overrode dryMass and/or fuelMass but did not also
    % explicitly override mass, keep mass consistent automatically.
    if ~isfield(overrides, 'mass') && ...
            (isfield(overrides, 'dryMass') || isfield(overrides, 'fuelMass'))
        params0.mass = params0.dryMass + params0.fuelMass;
    end

    % The MPC's vertical target is the COM height required for the bottom
    % tips of the landing legs to sit exactly on the pad.  Keep it derived
    % from the actual landing geometry so a future leg-height change cannot
    % reintroduce an altitude offset.
    if ~isfield(overrides, 'target') || ...
            ~isfield(overrides.target, 'centerHeight')
        params0.target.centerHeight = -params0.landerGeometry.footY;
    end

    validatePhysicsParameters(params0);

    state0 = [-60; 4; 120; -1.2; 0.08; 0];
end
